# @package _group_
_target_: src.domain_adaptation.models.adversarial-discriminative.PROVA_UNO.Prova_uno

name: "PROVA_UNO"
backbone: 'vit'
adversarial_network_width: 1024 
dropout_adversarial_network: True
source_classifier_width: 1024
dropout_classifier_network: True