# @package _group_
_target_: src.datamodule.datamodule.DataModule 

#LOTTO1
#"/raid/JUPYTERHUB-DIRS/shared/tlnext/domain_adaptation/datasets/oblocheck/LOTTO1/LEFT/"
#"/raid/JUPYTERHUB-DIRS/shared/tlnext/domain_adaptation/datasets/oblocheck/LOTTO1/RIGHT/"

#LOTTO2
# "/raid/JUPYTERHUB-DIRS/shared/tlnext/domain_adaptation/datasets/oblocheck/LOTTO2_2021_05_03-2021_05_13/LEFT/"
#  "/raid/JUPYTERHUB-DIRS/shared/tlnext/domain_adaptation/datasets/oblocheck/LOTTO2_2021_05_03-2021_05_13/RIGHT/"

source_domain_path :  "/raid/JUPYTERHUB-DIRS/shared/tlnext/domain_adaptation/datasets/oblocheck/LOTTO2_2021_05_03-2021_05_13/RIGHT/"
target_domain_path : "/raid/JUPYTERHUB-DIRS/shared/tlnext/domain_adaptation/datasets/oblocheck/LOTTO1/LEFT/"
dataset_type: oblocheck
name_source_domain: LOTTO2_RIGHT
name_target_domain: LOTTO1_LEFT
n_class: 2
batch_size : 32 
num_workers: 5
validation_split: 0.
num_sample_test_embeddings_projector: 1 #multiple of 384
data_processing:
  resize_size: 256 #256, 384(ViT)
  mean: [0.485, 0.456, 0.406]
  std: [0.229, 0.224, 0.225]
data_augmentation: 
  resize_crop_size: 224
  p: 0.5 #set to 0 when using ViT as backbone


# DATASETS NAME
#Office-31: amazon, webcam, dslr